# Generated by Django 4.0.4 on 2022-04-20 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_auto_20200808_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='HarryGuestHouse',
            new_name='hotel',
        ),
    ]
