# Generated by Django 4.0.4 on 2022-04-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_rooms_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='payment_method',
            field=models.CharField(choices=[('Cash On Checkout', 'Cash On Checkout'), ('Khalti', 'Khalti')], max_length=50),
        ),
    ]
