# Generated by Django 4.0.4 on 2022-04-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_rooms_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='payment_status',
            field=models.IntegerField(default=1),
        ),
    ]
