# Generated by Django 4.0.4 on 2022-04-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_reservation_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
