# Generated by Django 3.2.4 on 2022-04-25 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_rooms_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='guest_count',
            field=models.IntegerField(default=1),
        ),
    ]
